In [73]:
import torch
import numpy as np
rand_mat = torch.rand(5, 5)
adj_mat = torch.tensor([[0,1,1,0,1,],
                        [1,0,0,0,1,],
                        [1,0,0,1,0,],
                        [0,0,1,0,0,],
                        [1,1,0,0,1,]])
rand_mat = rand_mat*adj_mat
print(rand_mat)
k_th_quant = torch.topk(rand_mat, 3)[0][:,-1:]
print(k_th_quant)
mask = (rand_mat > k_th_quant)/1
temp = mask.count_nonzero(dim=1)
shape = temp.size()
temp = temp.view(shape[0],1)
print(shape)
print(temp)
print(mask)
mask = mask/temp

mask

tensor([[0.0000, 0.6386, 0.7589, 0.0000, 0.5655],
        [0.5201, 0.0000, 0.0000, 0.0000, 0.6312],
        [0.0763, 0.0000, 0.0000, 0.4781, 0.0000],
        [0.0000, 0.0000, 0.4768, 0.0000, 0.0000],
        [0.9530, 0.2684, 0.0000, 0.0000, 0.4343]])
tensor([[0.5655],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.2684]])
torch.Size([5])
tensor([[2],
        [2],
        [2],
        [1],
        [2]])
tensor([[0., 1., 1., 0., 0.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 1.]])


tensor([[0.0000, 0.5000, 0.5000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000, 0.0000, 0.5000],
        [0.5000, 0.0000, 0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 1.0000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000, 0.0000, 0.5000]])

tensor([[0.3882, 0.4394, 0.5083],
        [0.9964, 0.8606, 1.1735],
        [1.5027, 0.7491, 1.6142],
        [0.8450, 0.4340, 0.7593],
        [1.1039, 0.7603, 1.0660]])